### ISSUE TITLE
ApiError (No upload url could be obtained for part XXX

### ISSUE THREAD

**Issue by MichalGrzegorzak** [Steffens-Bridgemate/WeTransfer-C-wrapper#2] opened 2019-02-06 10:14 UTC
For larger uploads (> 100MB ?) I'm always receiving such error:
UploadUrl: ApiError (No upload url could be obtained for part XX.).

On API v1 - it totally blocks uploads, 
on API v2 - I'm retrying the transfer and it continues fine.

But I don't understand why / what at is the problem?

**Comment by Steffens-Bridgemate** [comment] 2019-02-06 20:44
Hello Michal,

Unfortunately, I cannot reproduce the issue with the V2 API. I succesfully sent a 329MB file, cut in 68 chuncks. What you can do is examine the response from the RequestUploadUrl function to see if the WeTransfer webservice has included a meaningful reply why the upload url was not provided.

**Comment by Steffens-Bridgemate** [comment] 2019-02-25 19:36
I will close this issue for now, as no further comments have been put forward.

**Closed as completed** 2019-02-25 19:35 UTC
